version: '3.8'

services:
  startio:
    container_name: startio
    image: startio:0.0.1-SNAPSHOT
    restart: always
    ports:
      - 8081:8080
  postgresql:
    image: 'bitnami/postgresql:latest'
    volumes:
      - "./initDB.sql:/docker-entrypoint-initdb.d/1.sql"
    restart: always
    ports:
      - '5432'
#    environment:
#      MYSQL_ROOT_PASSWORD: #add root password
#      MYSQL_USER: consumerz
#      MYSQL_PASSWORD: # add password