server:
  port: 8080

spring:
  application:
    name: consumerz
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/consumerz
    username: postgres
    password: unix11
  jpa:
    database-platform: org.hibernate.dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
